config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, :controllers => {:registrations => "registrations"}
  resources :optional_modules
  get 'home/contactus'
  root 'home#index'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :email, :encrypted_password, :name, presence: true
         has_many :accounts_optional_modules
         has_many :optional_modules, through: :accounts_optional_modules
end

app/models/accounts_optional_module.rb
class AccountsOptionalModule < ApplicationRecord
    belongs_to :account
    belongs_to :optional_module
    validates :account_id, :optional_module_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/optional_module.rb
class OptionalModule < ApplicationRecord

    validates :name, :description, presence: true
    has_many :accounts_optional_modules
    has_many :accounts, through: :accounts_optional_modules
end

app/controllers/accounts_optional_module_controller.rb
class AccountsOptionalModule < ApplicationController
  before_action :set_accounts_optional_module, only: [:show, :edit, :update, :destroy]

  def index
    @accounts_optional_modules = AccountsOptionalModule.all
  end

  # GET /optional_modules/1
  # GET /optional_modules/1.json
  def show
  end

  # GET /optional_modules/new
  def new
    @accounts_optional_module = AccountsOptionalModule.new
  end

  # GET /optional_modules/1/edit
  def edit
  end

  def create
        @optional_module_id = OptionalModule.find(params[:optional_module_id])
        @account_id = Account.find(params[:account_id])
        @enrolment = AccountsOptionalModule.new(@account_id, @optional_module_id)
        respond_to do |format|
            if @enrolment.save
                format.html { redirect_to @enrolment, notice: 'You have enrolled successfully!' }
                format.json { render :show, status: :created, location: @enrolment }
            else
                format.html { render :new }
                format.json { render json: @enrolment.errors, status: :unprocessable_entity }
            end
        end
    end

  def destroy
    @account_optional_module.destroy
    respond_to do |format|
      format.html { redirect_to optional_modules_url, notice: 'Successfully unenrolled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_optional_module
      @account_optional_module = AccountOptionalModule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_optional_module_params
      params.require(:account_optional_module).permit(:account_id, :optional_module_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contactus
  end
  
end

app/controllers/optional_modules_controller.rb
class OptionalModulesController < ApplicationController
  before_action :set_optional_module, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:destroy]

  # GET /optional_modules
  # GET /optional_modules.json
  def index
    @optional_modules = OptionalModule.all
  end

  # GET /optional_modules/1
  # GET /optional_modules/1.json
  def show
  end

  # GET /optional_modules/new
  def new
    @optional_module = OptionalModule.new
  end

  # GET /optional_modules/1/edit
  def edit
  end

  # POST /optional_modules
  # POST /optional_modules.json
  def create
        @optional_module = OptionalModule.find(params[:optional_module_id])
        @account = Account.find(params[:account_id])
        @accounts_optional_module = AccountsOptionalModule.new(account_id: @account, optional_module_id: @optional_module)
        respond_to do |format|
          if @account.optional_modules << @optional_module
            AccountMailer.with(account: @account).enrol_email.deliver_now
            format.html { redirect_to optional_modules_path, notice: 'Enrolled successfully!.' }
            format.json { render :show, status: :ok, location: @accounts_optional_module }
          else
            format.html { render :edit }
            format.json { render json: @accounts_optional_module.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /optional_modules/1
  # PATCH/PUT /optional_modules/1.json
  def update
    respond_to do |format|
      if @optional_module.update(optional_module_params)
        format.html { redirect_to @optional_module, notice: 'Optional module was successfully updated.' }
        format.json { render :show, status: :ok, location: @optional_module }
      else
        format.html { render :edit }
        format.json { render json: @optional_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /optional_modules/1
  # DELETE /optional_modules/1.json
  def destroy
    @optional_module = OptionalModule.find(params[:id])
    @account = Account.find(current_account.id)
    @account.optional_modules.delete(@optional_module)
    respond_to do |format|
      format.html { redirect_to optional_modules_path, notice: 'Successfully Unenrolled!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_optional_module
      @optional_module = OptionalModule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def optional_module_params
      params.require(:optional_module).permit(:name, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
private

  def sign_up_params
    params.require(:account).permit(:email, :password, :password_confirmation, :name)
  end

  def account_update_params
    params.require(:account).permit(:email, :password, :password_confirmation, :current_password, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/optional_modules_helper.rb
module OptionalModulesHelper
end

app/views/home/_footer.html.erb
<footer>
      <div class="row">
        <div class="col span-1-of-2">
          <ul class="footer-nav">
            <li><a href="#">About us</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Press</a></li>
            <li><a href="#">iOS app</a></li>
            <li><a href="#">Android app</a></li>
          </ul>
        </div>
        <div class="col span-1-of-2">
          <ul class="social-links">
            <li>
              <a href="#"><i class="ion-social-facebook"></i></a>
            </li>
            <li>
              <a href="#"><i class="ion-social-twitter"></i></a>
            </li>
            <li>
              <a href="#"><i class="ion-social-googleplus"></i></a>
            </li>
            <li>
              <a href="#"><i class="ion-social-instagram"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <p>
          Copyright &copy; 2020 by COM2025 University. All rights reserved.
        </p>
      </div>
    </footer>

app/views/home/_header.html.erb
<nav>
  <div class="">
    <%= image_tag("logo.svg", :alt => "logo", class:"logo") %>
    <ul class="main-nav ml-auto">
      <% if account_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Sign Out', destroy_account_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_account_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Modules', optional_modules_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact Us', home_contactus_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'Sign Up', new_account_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Log In', new_account_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/contactus.html.erb
<body>
    <section class="section-form">
      <div class="row">
        <h2 class="modules">We're happy to hear from you</h2>
      </div>
      <div class="row">
        <form method="POST" action="#" class="contact-form">
          <div class="row">
            <div class="col span-1-of-2">
              <label for="name">Name</label>
            </div>
            <div class="col span-2-of-2">
              <input
                type="text"
                name="name"
                id="name"
                placeholder="Your name"
                required
              />
            </div>
          </div>
          <div class="row">
            <div class="col span-1-of-2">
              <label for="email">Email</label>
            </div>
            <div class="col span-2-of-2">
              <input
                type="email"
                name="email"
                id="email"
                placeholder="Your email"
                required
              />
            </div>
          </div>
          <div class="row">
            <div class="col span-1-of-2">
              <label for="find-us">How did you find us?</label>
            </div>
            <div class="col span-2-of-2">
              <select name="find-us" id="find-us">
                <option value="friends" selected>Friends</option>
                <option value="search">Search engine</option>
                <option value="ad">Advertisement</option>
                <option value="other">Other</option>
              </select>
            </div>
          </div>
          <div class="row">
            <div class="col span-1-of-2">
              <label>Newsletter</label>
            </div>
            <div class="col span-2-of-2">
              <input type="checkbox" name="news" id="news" checked /> Yes
              please!
            </div>
          </div>
          <div class="row">
            <div class="col span-1-of-2">
              <label>Drop us a message</label>
            </div>
            <div class="col span-2-of-2">
              <textarea name="message" placeholder="Your message"></textarea>
            </div>
          </div>
          <div class="row">
            <div class="">
              <label> &nbsp;</label>
            </div>
            <div class="">
              <input type="submit" value="Send it!" />
            </div>
          </div>
        </form>
      </div>
    </section>
</body>

app/views/home/index.html.erb
<body>
    <header>
      <div class="hero-text-box">
        <h1>
          Goodbye boring life. <br/>
          Hello super fun modules.
        </h1>
        <a class="btn btn-full js--scroll-to-plans" href="/accounts/sign_up">I wanna learn!</a>
        <a class="btn btn-ghost js--scroll-to-start" href="#features">Show me more</a>
      </div>
    </header>

    <section class="section-features js--section-features" id="features">
      <div class="row">
        <h2 class="headertext">Get learning fast!</h2>
        <p class="long-copy">
          Hello, we're COM2025 University, your new state of the art online university! Here, you will be able
          to enrol in all sorts of online optional modules whilst carrying on with your current major degree. Enrol
          in some modules and have fun whilst learning at the same time, we promise!
        </p>
      </div>
      <div class="row">
        <div class="col span-1-of-4 box">
        <i class="ion-happy-outline icon-big"></i>
          <h3>Make Friends</h3>
          <p>
            Join lots of other people doing these optional modules and
            make new friends! What better way to make good friends when
            you can find other people that like the same things as you!
          </p>
        </div>
        <div class="col span-1-of-4 box">
          <i class="ion-ios-stopwatch-outline icon-big"></i>
          <h3>Just 30 minutes a day</h3>
          <p>
            You only need to commit 30 minutes a day to properly take part
            in these super fun optional modules. We work with the best teachers
            to ensure your learning is as efficient as possible!
          </p>
        </div>
        <div class="col span-1-of-4 box">
          <i class="ion-planet icon-big"></i>
          <h3>Anywhere anytime</h3>
          <p>
            Complete our optional modules whenever and wherever in the world. Even if
            you start in London you can complete it in a different country if
            you want! Whatever works best for you!
          </p>
        </div>
        <div class="col span-1-of-4 box">
          <i class="ion-trophy icon-big"></i>
          <h3>certificates</h3>
          <p>
            Don't worry! You'll get a certificate upon completion of each optional 
            module, so you can always write it down in your CV with the proof to back
            it up. Let's grow the collection!
          </p>
        </div>
      </div>
    </section>

    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="vendors/js/jquery.waypoints.min.js"></script>
    <script src="resources/js/script.js"></script>
  </body>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>COM2025 University</title>

    <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,300&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"
    />

  </head>
  <body>
    <div>
      <%= render 'home/header' %>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
      <%= render 'home/footer' %>
    </div>  
  
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
  </body>
</html>

app/views/optional_modules/_form.html.erb
<%= form_with(model: optional_module, local: true) do |form| %>
  <% if optional_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(optional_module.errors.count, "error") %> prohibited this optional_module from being saved:</h2>

      <ul>
      <% optional_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/optional_modules/edit.html.erb
<h1>Editing Optional Module</h1>

<%= render 'form', optional_module: @optional_module %>

<%= link_to 'Show', @optional_module %> |
<%= link_to 'Back', optional_modules_path %>

app/views/optional_modules/index.html.erb
<body>
  <section class="module">
    <div class="row">
      <h2 class="modules">Optional Modules</h2>
    </div>
    <div class="row">
      <% @optional_modules.each do |optional_module| %>
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= optional_module.name %></h4>
          <p class="card-text"><%= optional_module.description %></p>
            <% if current_account.optional_modules.exists?(optional_module.id)%>
              <%= button_to 'Unenrol', optional_module_path(optional_module.id), method: :delete, data: { confirm: 'Are you sure?'} %>
            <% else %>
              <%= button_to 'Enrol', {:action => "create"}, params: {:account_id => current_account.id, :optional_module_id => optional_module.id} %>
            <% end %>
        </div>
        <br/>
      </div>
      <% end %>
    </div>
  </section>
</body>

app/views/optional_modules/new.html.erb
<h1>New Optional Module</h1>

<%= render 'form', optional_module: @optional_module %>

<%= link_to 'Back', optional_modules_path %>

app/views/optional_modules/show.html.erb
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h4 class="card-title"><%= @optional_module.name %></h4>
    <p class="card-text"><%= @optional_module.description %></p>
    <a href="#" class="btn btn-primary">Enrol</a>
  </div>
</div>

<%= link_to 'Edit', edit_optional_module_path(@optional_module) %> |
<%= link_to 'Back', optional_modules_path %>